version: '1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
    - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - /elastic/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - /elastic/elasticsearch/data/:/usr/share/elasticsearch/data
    networks:
    - elk
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
    - /elastic/kibana/config/:/etc/kibana/
    networks:
    - elk
    depends_on:
     - elasticsearch
     
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    container_name: logstash
    volumes:
    - /elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    - /elastic/logstash/pipeline:/usr/share/logstash/pipeline
    ports:
    - 5040:5040
    environment:
    - "LS_JAVA_OPTS= -Xms1G -Xmx1G"
    networks:
    - elk
    depends_on:
    - elasticsearch

networks:
  elk:
    driver:bridge
