version: '3.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ./esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
    networks: 
    - elk
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    ports:
    - 5601:5601
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks: 
    - elk
    depends_on:
    - elasticsearch
     
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    container_name: logstash
    environment:
    - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./lspipeline:/usr/share/logstash/pipeline
    ports:
    - 5040:5040
    - 9600:9600
    networks: 
    - elk
    depends_on:
    - elasticsearch
    
networks:
  elk:
    driver: bridge

